FROM ubuntu:22.04

LABEL Maintainer="Gee-Him Siu <gsiu@monevo.com"
LABEL Description="PHP-FPM & Nginx built into ubuntu"

RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates



RUN export DOCKER_DEFAULT_PLATFORM=linux/amd64

ENV TZ=UTC
ENV DEBIAN_FRONTEND=noninteractive

# Corporate network compatibility - skip PPA repositories and use Ubuntu defaults
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y software-properties-common tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# Use Ubuntu default PHP 8.1 instead of PPA PHP 8.3 (corporate network compatible)
RUN apt-get update

RUN apt-get purge apache2 -y
RUN apt-get install -y \
    mariadb-client \
    supervisor \
    nginx \
    php8.1 \
    php8.1-fpm \
    php8.1-dev \
    php8.1-curl \
    php8.1-gd \
    php8.1-xml \
    php8.1-dom \
    php8.1-common \
    php8.1-mysql \
    php8.1-zip \
    php8.1-intl \
    php8.1-bcmath \
    php8.1-mbstring \
    php8.1-soap \
    php8.1-redis

COPY ./config/supervisord.conf /etc/supervisor/conf.d/web.conf
COPY ./config/enabled.conf /etc/nginx/sites-enabled/default
COPY ./config/enabled.conf /etc/nginx/sites-available/default
COPY ./config/www.conf /etc/php/8.1/fpm/php-fpm.conf

COPY .env /var/www/.env
COPY ./src /var/www/public
COPY ./config.sh /var/www/config.sh

# Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN chmod 755 /var/www/config.sh
RUN /var/www/config.sh

CMD ["/usr/bin/supervisord"]

#RUN mkdir /var/www/public/application/logs
RUN chown -R www-data.www-data /var /run
#RUN chmod 775 /var/www/public
#RUN chmod 640 /var/www/.env

USER www-data

WORKDIR /var/www

EXPOSE 8080
