FROM ubuntu:22.04

LABEL Maintainer="Gee-Him Siu <gsiu@monevo.com"
LABEL Description="PHP-FPM & Nginx built into ubuntu"

RUN export DOCKER_DEFAULT_PLATFORM=linux/amd64

ENV TZ=UTC
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y software-properties-common tzdata && \
    echo | add-apt-repository ppa:ondrej/php && \
    echo | add-apt-repository ppa:ondrej/nginx && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

RUN apt-get purge apache2 -y
RUN apt-get install -y \
    mariadb-client \
    supervisor \
    nginx \
    php8.3 \
    php8.3-fpm \
    php8.3-dev \
    php8.3-tokenizer \
    php8.3-curl \
    php8.3-gd \
    php8.3-fileinfo \
    php8.3-xml \
    php8.3-phar \
    php8.3-dom \
    php8.3-common \
    php8.3-mysql \
    php8.3-exif \
    php8.3-zip \
    php8.3-intl \
    php8.3-iconv \
    php8.3-bcmath \
    php8.3-mbstring \
    php8.3-pdo \
    php8.3-pdo \
    php8.3-soap \
    php8.3-redis \
    php8.3-gearman

COPY ./config/supervisord.conf /etc/supervisor/conf.d/web.conf
COPY ./config/enabled.conf /etc/nginx/sites-enabled/default
COPY ./config/enabled.conf /etc/nginx/sites-available/default
COPY ./config/www.conf /etc/php/8.3/fpm/php-fpm.conf

COPY .env /var/www/.env
COPY ./src /var/www/public
COPY ./config.sh /var/www/config.sh

# Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN chmod 755 /var/www/config.sh
RUN /var/www/config.sh

CMD ["/usr/bin/supervisord"]

#RUN mkdir /var/www/public/application/logs
RUN chown -R www-data.www-data /var /run
#RUN chmod 775 /var/www/public
#RUN chmod 640 /var/www/.env

USER www-data

WORKDIR /var/www

EXPOSE 8080
